### ISSUE TITLE
Create frontend-backend abstraction facade

### ISSUE THREAD

**Issue by Otann** [Otann/owlunit-web#17]
So there is frontend (lift) and backend (ii-core).
Frontend wants to manipulate with high-level objects like users, movies and actors.
On other side backend knows nothing about concrete usage of information items.

Right now this is implemented in ii-service maven artefact, but needs to be reimplemented in scala.

**Comment by ilya-pimenov** [comment]
Anton: Да я знаю, задача говно
Че дальше
Ilya: я прикидываю хер к носу, смотрю в код и вижу что возвращаются коллекции объектов InformationItem
все использования TagService и Recommender из пакета com.manymonkeys.app.page.*
вписываются в функиональный подход предельно гладко
единственное - можно было бы переписать c Map.Entry возвращаемые значения на ( , ) - как они там называются не помню в Scala
и то же самое с InformationItem
Anton: К чему это все?
Ilya: но это если вдруг надо будет делать match и только
Anton: А, понял
Ilya: а теперь к чему - в результате этой деятельности: переписывания ii-service пакета на scala - никакого профита не будет. оно станет только медленее собираться и придется переписывать краулеры
Anton: Закрой и напиши: нахуй не всралось, пока сойдет и так
Ilya: является ли текущее состояние бэкенда проблемой для написания фронтенда? - вообще нет
