### ISSUE TITLE
Greasemonkey plugin

### ISSUE THREAD

**Issue by Otann** [Otann/owlunit-web#26]
Написать плагин для Greasemonkey для инъекций похожих фильмов в страницу Yota Play.

Страницы для инъекций:
-  Страница фильма, например http://yotaplay.ru/main#movie/menjajushchierealnost  
  - Грабить информацию о фильме и сливать нам
  - Показывать похожие фильмы
  - Если есть залогиненый пользователь, грабить его, его оценку фильму и учитывать его в рекомендациях
-  Страница рекомендаций http://yotaplay.ru/main#recommended и главная страница http://yotaplay.ru/main#home
  - Показывать рекомендованные фильмы для пользователя (Owl считает, что вам так же понравятся эти фильмы...)

Сложить все в папку `/ex-yotaplay`

**Comment by nichtverstehen** [comment]
https://github.com/Otann/ii/blob/master/ex-yotaplay/iiPlay.crx
Первая версия есть. Показывается список похожих фильмов на странице фильма yotaplay.

**Comment by nichtverstehen** [comment]
Теперь нужно прояснить следующее:
- Куда должны вести ссылки фильмов (как получить по нашему id фильма етин id)?
- Нужно ли показывать похожие на страница сериала, серии, сезона?
- Где взять картинки/превьюшки для фильмов?

**Comment by Otann** [comment]
- пока никуда, это необязательно, но можно попробовать достать его из "быстрого поиска"
- пока нет, у нас нет в базе сериалов
- Илья добавит ссылку на картинку-рыбу в ближайшем апдейте

**Comment by nichtverstehen** [comment]
Текущее состояние:
- Ссылки фильмов ведут на поиск этого фильма
- Картинки отображаются

**Comment by Otann** [comment]
moved to jura
