### ISSUE TITLE
Поднять CI

### ISSUE THREAD

**Issue by Otann** [Otann/owlunit-web#27]
Поднять Continious Integration (Teamcity) на окружении
Доступ к машинам смотри на https://github.com/Otann/ii/wiki/Environment

**Comment by morj** [comment]
TeamCity работает на http://home.chebotaev.ru:8080/buildserver/overview.html
Бесплатная версия (Maximum 20 build configurations, Includes 3 build agents for free)
Для стабильной работы встроенная в TC база заменена на MySQL 5.1.49 (добавил инфу о её исталляции в вики https://github.com/Otann/ii/wiki/Environment)

Создал пользователей-админов для себя, Антона (otann) и Ильи (badmotherfucker) c с паролями owl2011 (предлагаю каждому свой поменять).
Создал билд-конфигурацию, запускающую pom.xml (что-то она падает с ошибкой из мавена "No versions are present in the repository for the artifact with a range" http://home.chebotaev.ru:8080/buildserver/viewType.html?buildTypeId=bt3&tab=buildTypeStatusDiv).

**Comment by morj** [comment]
По любому коммиту в ремоутный мастер на гитхабе эта конфигурация будет автоматически запускаться.

**Comment by morj** [comment]
Кстати, проверьте настройки юзенейма в гите в ваших профилях на тимсити, чтобы табик My Changes http://home.chebotaev.ru:8080/buildserver/changes.html правильно отображался.
