### ISSUE TITLE
Исправить логгирование в кроулерах

### ISSUE THREAD

**Issue by Otann** [Otann/owlunit-web#35]
Не работает, но очень нужно.
Еще отлично будет отключить лог кассандры, который продирается в stdout.

**Comment by ilya-pimenov** [comment]
Настроил новую систему подлогирования, log4j была  объявлена derecated by owner, из-за проблем при параллельной разработке. Также начал выносить зависимости (пока соответственно только логгирование) в родительский pom, через DependencyManagement. Теперь все версии будут только в родителе, а в детях только объявление, что такой артифакт используется, без версии - она резолвится через родителя.
