### ISSUE TITLE
Создать класс-обертку вокруг DIV для объекта Keyword (общий Ii)

### ISSUE THREAD

**Issue by ilya-pimenov** [Otann/owlunit-web#38]
Объект который будет уметь нормально рендериться в наш правильный брендованный Ii. Как пример, можно смотреть на Apache Click Controllers, полный список тут — http://click.apache.org/docs/click-api/org/apache/click/control/package-summary.html.

Как пример внедрения, на странице InviteLandingPage обернуть в них список predefinedKeywords для приглашенного пользователя.

**Comment by Otann** [comment]
rejected
