### ISSUE TITLE
Сделать вывод главного меню приложения через VelocityMacros

### ISSUE THREAD

**Issue by ilya-pimenov** [Otann/owlunit-web#39]
Сейчас главное меню рендерится через $rootMenu в border-template.htm, там все подхватывается из дефолтной поставки.

Как это делать в целом, написано тут — http://click.apache.org/docs/extras-api/org/apache/click/extras/control/Menu.html в части "Alternatively, you can render the menu using a Velocity #macro or Velocity code in your template. For example: ".

Причина — нам надо будет выводить кастом элементы у отдельных пунктов меню, и в целом в дальнейшем сделать его "сильно дохуя smart".

**Comment by Otann** [comment]
rejected
