### ISSUE TITLE
Сделать "листаемые" invite-divы на InviteLandingPage

### ISSUE THREAD

**Issue by ilya-pimenov** [Otann/owlunit-web#40]
Подключать JavaScript через getHeadElements().add(new JsImport()) в классе страницы.

"Листаться" должны так как ты предполагал в 

> Пользователь открыл ссылку из письма с инвайтом и увидел экран приветствия
> (листаемый вправо-влево), на котором отображается описание сервиса, список
> подготовленных для него айаев и кнопка аторизации фэйсбуком.

Если потребуется использование сторонних библиотек кроме jQuerry — отписать об этом alarm.

**Comment by Otann** [comment]
rejected
