### ISSUE TITLE
Выпилить Scala из доменных классов User, Movie, ... (перевести их в POJO)

### ISSUE THREAD

**Issue by ilya-pimenov** [Otann/owlunit-web#41]
Причина в InvitedUserServiceMock.isInvitedUser(). Что-то странное с поддержкой языка, или с фактическим наличием getМетодов у этих объектов, они не видны в наследних, что ломает все проверки контракта compile-time.

Изначально мы их так написали чтобы позднее использовать красиво в матчерах в Scala. Сейчас необходимости нет, содает только добавочную complexity в общий стэк технологий. In general — надо пока убрать Scala в проектах которые собираются если ты набираешь "mvn clean install" в директории /ii (там где parent-pom).

**Comment by Otann** [comment]
rejected
