### ISSUE TITLE
Строить аккуратно соответствия названий фильмов из facebook к фильмам (ii-ям) хранящимся в нашей базе данных и сохранить полученную о пользователе информацию в базе данных

### ISSUE THREAD

**Issue by ilya-pimenov** [Otann/owlunit-web#42]
Соответствие и сохранение происходит в методе MoviesstoryServiceImpl.importUserFacebookMovies(). В настойщий момент просто создаются объекты Movie с именем фильма полученного из профиля пользователя.

После этого надо 
1) сохранить полученные связи на новые фильмы, для этого пользователя
 2) и записать данные в watchlist (его надо будет поддержать на подобии InvitedUser, будет уже представлен на 4-ом шаге полного сценария посещения сайта)

**Comment by Otann** [comment]
decomposed to jira
