### ISSUE TITLE
Имплементировать импорт личных данных из facebook

### ISSUE THREAD

**Issue by ilya-pimenov** [Otann/owlunit-web#43]
Для примера можно воспользоваться методом MoviesstoryServiceImpl.importUserFacebookMovies() — он импортирует данные о фильмах пользователя с фэйсбука.

Сам метод находится в сервисе MoviesstoryServiceImpl.importUserFacebookData(), вызывается в переходах на странице приглашения.

**Comment by Otann** [comment]
wtf?
